name: 'Terraform Test'
run-name: ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
    inputs:
      # The name of the GitHub environment to reference
      environment:
        default: dev
        description: 'Environment:'
        required: true
        type: string

env:
  # Use the environment-specific state file for Terraform init commands
  TF_CLI_ARGS_init: |
    -backend-config="subscription_id=${{ vars.ARM_SUBSCRIPTION_ID }}"
    -backend-config="resource_group_name=${{ vars.TF_STATE_RESOURCE_GROUP_NAME }}"
    -backend-config="storage_account_name=${{ vars.TF_STATE_STORAGE_ACCOUNT_NAME }}"
    -backend-config="container_name=${{ vars.TF_STATE_CONTAINER_NAME }}"
    -backend-config="key=${{ inputs.environment}}.tfstate"

  # Disable Terraform input prompts and user-mode output
  TF_IN_AUTOMATION: true
  TF_INPUT: 0

  # Enable Terraform debug logging if GitHub Actions step debugging is enabled
  TF_LOG: ${{ secrets.ACTIONS_STEP_DEBUG == 'true' && 'DEBUG' || 'ERROR' }}

jobs:
  test:
    name: 'Terraform Test'
    runs-on: [self-hosted, linux, x64]
    environment:
      name: ${{ inputs.environment }}

    env:
      # Required for Terraform service principal authentication
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v3

      # Use a custom access token for access to dependant private repos
      - name: Configure Git
        run: |
          echo "Configuring git for custom PAT..."
          git config --global url."https://oauth2:${{ secrets.TERAS_PAT }}@github.com".insteadOf https://github.com

      # Install Terraform on the runner agent
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Login to Azure using the service principal credentials
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ env.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ env.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ env.ARM_TENANT_ID }}"}'

      # Initalise Terraform
      - name: Terraform Init
        run: |
          echo "Initializing Terraform..."
          terraform init -no-color

      # Run Terraform test
      - name: Terraform Test
        run: |
          terraform test
